# Serving
detach:  false
port:    3000
host:    0.0.0.0
baseurl: "" # BLANK for local or domain based, /dotcom for github pages

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Custom collections
collections:
  videos:
    output: false

# Site settings
title: Beard & Fedora
tagline: Idea Makers - Story Tellers - Life Experiencers
email: badassery@beardandfedora.com
description: "We are a Beard and a Fedora. We make things. We also write things. We also travel."
# Pssst..we edit the above line in _config.yml. It will appear in our document head meta (for Google search results) 
# and in our feed.xml site description.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8e44ad #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  tirtuary: 9b59b6 #FD6E8A
  tirtuary-dark: 95a5a6 #A2122F
  body-bg: ecf0f1
  bg: ecf0f1
  btn-success: 27AE60
  btn-success-hover: 2ECC71
  btn-primary: 8e44ad
  btn-primary-hover: 9B59B6
  btn-info: BDC3C7
  btn-info: 95A5A6
  btn-warning: D35400
  btn-warning-hover: E67E22
  brn-danger: C0392B
  brn-danger-hover: C0E74C3C392B

# Footer settings
footer:
  copyleft: Beard & Fedora
  location: Location
  social: Around the Interwebs
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#  See http://fortawesome.github.io/Font-Awesome/icons/
# For options example: fa-spin | see http://fortawesome.github.io/Font-Awesome/examples/ for more info
social:
  - title: Beard & Fedora on Github
    site: github
    url: http://github.com/BeardandFedora
  - title: Beard & Fedora on Facebook
    site: facebook
    url: http://facebook.com/BeardandFedora
  - title: Beard & Fedora on Twitter
    site: twitter
    url: http://twitter.com/BeardandFedora
  - title: Fedora on Behance
    site: behance
    url: http://be.net/thinq4yourself
  - title: Fedora on Angel List
    site: angellist
    url: http://angel.co/joel-serino
  - title: Fedora on LinkedIn
    site: linkedin
    url: http://lnkd.in/9tetJY
  - title: Beard on the Web
    site: html5
    url: http://tylergoelz.com
  - title: Beard on Angel List
    site: angellist
    url: https://angel.co/tylergoelz
  - title: Beard on LinkedIn
    site: linkedin-square
    url: http://www.linkedin.com/in/tylergoelz

# Location info (add as many lines as necessary)
location:
  - line: <a href="http://twitter.com/tylergoelz" target="blank" class="text-success">Beard</a> | <i class="fa fa-map-marker text-success"></i> On The Road
  - line: <a href="http://twitter.com/thinq4yourself" target="blank" class="text-danger">Fedora</a> | <i class="fa fa-map-marker text-danger"></i> On The Road

# Credits content
credits: 'This is <a href="https://github.com/BeardandFedora/dotcom" target="blank">free to use</a>, <a href="http://opensource.org/" target="blank">open source</a>, and in the <a href="https://creativecommons.org" target="blank">creative commons</a>. Built using Jekyll, Bootstrap, Flat UI, and Github.'